### ISSUE TITLE
ValidationError in v4

### ISSUE THREAD

**Issue by gunar** [aexmachina/factory-girl#75] opened 2016-10-26 20:36 UTC
I've upgraded to v4 and now I can't pass ObjectIds into `create` functions.

``` js
  factory.create('car', { owner: owner.id }) // this works
  factory.create('car', { owner }) // this does NOT
  factory.create('car', { owner: owner._id }) // this does NOT
```

Error

```
message: 'Car validation failed',
name: 'ValidationError',
errors:
 { capability:
    { CastError: Cast to ObjectID failed for value "{ id:
       { '0': 88,
         '1': 17,
         '2': 19,
         '3': 3,
         '4': 54,
         '5': 228,
         '6': 171,
         '7': 60,
         '8': 100,
         '9': 82,
         '10': 176,
         '11': 71 },
      _bsontype: 'ObjectID' }" at path "owner"
        at MongooseError.CastError (/home/test/node_modules/mongoose/lib/error/cast.js:26:11)
```

**Comment by chetanism** [comment] 2016-10-27 16:51
Hi @gunar, it would help if you can provide more details to reproduce the issue, a sample project would be awesome! Otherwise I'll to reproduce this as soon as I can find some free time.

**Comment by gunar** [comment] 2016-10-28 15:19
```js
'use strict'

const mongoose = require('mongoose')
const FactoryGirl = require('factory-girl')

mongoose.connect('mongodb://localhost:27017/factory-girl-test', {})

mongoose.Promise = global.Promise

const factory = FactoryGirl.factory
const adapter = new FactoryGirl.MongooseAdapter();
factory.setAdapter(adapter);

const { Schema } = mongoose

const Email = mongoose.model('Email', new Schema({
  subject: String,
  thread: { type: Schema.Types.ObjectId, ref: 'Thread' },
}))
factory.define('email', Email, {
  thread: factory.assoc('thread', '_id'),
})

const Thread = mongoose.model('Thread', new Schema({}))
factory.define('thread', Thread, {})

factory.create('thread').then(thread =>
  factory.create('email', { thread: thread._id }).then(email =>
    console.log('success!')))
```
```
(node:30824) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Valid
ationError: CastError: Cast to ObjectID failed for value "{ id:
   { '0': 88,
     '1': 19,
     '2': 107,
     '3': 192,
     '4': 231,
     '5': 210,
     '6': 197,
     '7': 120,
     '8': 104,
     '9': 2,
     '10': 109,
     '11': 227 },
  _bsontype: 'ObjectID' }" at path "thread"
```

**Comment by chetanism** [comment] 2016-10-28 20:36
Hi @gunar, I have probably found the issue. I have a fix that works for me, but I am not sure if it's the right way to go. I'll still raise a PR and let @aexmachina decide if it looks good to me merged.

**Comment by chetanism** [comment] 2016-10-28 20:56
@gunar, I have raised #79. You may want to try it out and update us if the fix works for you!

**Closed** 2017-04-10 05:17 UTC
